CSV_FILE_STORAGE_BUCKET='CSV_FILE_STORAGE_BUCKET'
DATA_INTEGRATION_PROJECT = 'DATA_INTEGRATION_PROJECT'
SUPPLIER_DATA_HUB_PROJECT = 'SUPPLIER_DATA_HUB_PROJECT'
JOB_ID_PREFIX="JOB_ID_PREFIX"
GCLOUD_PROJECT='GCLOUD_PROJECT'
# Query Params Filter

DC_FILTER="dc"
VALUE_FILTER="value"
PERIOD_FILTER="period"
YEAR_FILTER="year"
WEEK_COMMENCE_FILTER="weekCommencing"
OFFSET_FILTER="offset"
MAX_RESULTS_FILTER="limit"
USER_NAME="userName"
VENDOR_NUMBER="vendorNumber"
SUPPLIER_NAME="supplierName"

DEFAULT_DC_FILTER="all"
DEFAULT_VALUE_FILTER="units"
DEFAULT_PERIOD_FILTER="1 day"
DEFAULT_YEAR_FILTER="2020"
DEFAULT_WEEK_COMMENCE_FILTER="2021-08-10"
DEFAULT_OFFSET_FILTER=0
DEFAULT_MAX_RESULTS_FILTER=10
DEFAULT_USER_NAME="SDH"
DEFAULT_VENDOR_NUMBER="00000"
DEFAULT_SUPPLIER_NAME="NA"

# def formats

DATE_FORMAT = '%Y-%m-%d'

# String Constants
MESSAGE = 'message'
LOCATION = 'EU'
METHOD = 'method'
PATH = 'path'
SAVE = 'save'
TABLE = 'table_name'
PROJECT = 'data-supplierdatahub-dev'
DOWNLOAD = 'download'

#Custom Error Message
ERROR_METHOD_NOT_SUPPORTED="API Method Not Supported"
ERROR_METHOD_NOT_AUTHORIZED="You Are Not Authorized"
ERROR_METHOD_NOT_FOUND="Not Found"
ERROR_INVALID_PATH="Invalid path"
ERROR_NO_QUERY_FOUND="No query found for provided value or period"
ERROR_NO_CONTENT="No data to fetch"

# Error codes forerrors
ERROR_CODE_BAD_REQUEST = 400
ERROR_CODE_NOT_AUTHORIZED=403
ERROR_CODE_NOT_FOUND=404
ERROR_CODE_METHOD_NOT_SUPPORTED = 405
ERROR_CODE_GENERIC = 500

# Other success codes
HTTP_SUCCESS_CODE_200 = 200
HTTP_SUCCESS_CODE_201 = 201
HTTP_SUCCESS_CODE_204 = 204