GCLOUD_PROJECT = 'GCLOUD_PROJECT'
SECRET_NAME = 'SECRET_NAME'
BUCKET = 'BUCKET_NAME'
CONFIG_FILE_NAME = 'CONFIG_FILE_NAME'

ERROR_CODE_INTERNAL_ERROR = 500
ERROR_CODE_METHOD_NOT_SUPPORTED = 405
SUCCESS_CODE = 200
SENDER_MAIL = 'sender_mail'

ERROR_INTERNAL_SERVER = 'Internal server error'

